
CREATE TABLE tb_cliente (
    id BIGINT,
    nome VARCHAR(50) NOT NULL,
    cpf BIGINT NOT NULL,
    tel BIGINT NOT NULL,
    endereco VARCHAR(50) NOT NULL,
    numero BIGINT NOT NULL,
    cidade VARCHAR(50) NOT NULL,
    estado VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    CONSTRAINT pk_id_cliente PRIMARY KEY(id)
);

ALTER TABLE tb_cliente
ADD CONSTRAINT UK_CPF_CLIENTE UNIQUE (cpf);


CREATE TABLE tb_produto(
    id BIGINT,
    codigo VARCHAR(10) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    valor NUMERIC(10,2) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    CONSTRAINT pk_id_produto PRIMARY KEY(id)
);

ALTER TABLE tb_produto
ADD CONSTRAINT UK_CODIGO_PRODUTO UNIQUE (codigo);


CREATE TABLE tb_venda(
    id BIGINT,
    codigo VARCHAR(10) NOT NULL,
    id_cliente_fk BIGINT NOT NULL,
    valor_total NUMERIC(10,2) NOT NULL,
    data_venda TIMESTAMPTZ NOT NULL,
    status_venda VARCHAR(50) NOT NULL,
    CONSTRAINT pk_id_venda PRIMARY KEY(id),
    CONSTRAINT fk_id_cliente_venda FOREIGN KEY(id_cliente_fk) REFERENCES tb_cliente(id)
);

ALTER TABLE tb_venda
ADD CONSTRAINT UK_CODIGO_VENDA UNIQUE (codigo);

CREATE TABLE tb_produto_quantidade(
    id BIGINT,
    id_produto_fk BIGINT NOT NULL,
    id_venda_fk BIGINT NOT NULL,
    quantidade INT NOT NULL,
    valor_total NUMERIC(10,2) NOT NULL,
    CONSTRAINT pk_id_prod_venda PRIMARY KEY(id),
    CONSTRAINT fk_id_prod_venda FOREIGN KEY(id_produto_fk) REFERENCES tb_produto(id),
    CONSTRAINT fk_id_prod_venda_venda FOREIGN KEY(id_venda_fk) REFERENCES tb_venda(id)
);


CREATE SEQUENCE sq_cliente
START 1
INCREMENT 1
OWNED BY tb_cliente.id;

CREATE SEQUENCE sq_produto
START 1
INCREMENT 1
OWNED BY tb_produto.id;

CREATE SEQUENCE sq_venda
START 1
INCREMENT 1
OWNED BY tb_venda.id;

CREATE SEQUENCE sq_produto_quantidade
START 1
INCREMENT 1
OWNED BY tb_produto_quantidade.id;


SELECT V.ID AS ID_VENDA, V.CODIGO, V.ID_CLIENTE_FK, V.VALOR_TOTAL, V.DATA_VENDA, V.STATUS_VENDA,
       C.ID AS ID_CLIENTE, C.NOME, C.CPF, C.TEL, C.ENDERECO, C.NUMERO, C.CIDADE, C.ESTADO, C.EMAIL,
       PQ.ID AS ID_PROD_QTD, PQ.QUANTIDADE, PQ.VALOR_TOTAL AS PROD_QTD_VALOR_TOTAL,
       P.ID AS ID_PRODUTO, P.CODIGO, P.NOME AS PROD_NOME, P.DESCRICAO AS PROD_DESCRICAO, P.VALOR AS PROD_VALOR, P.CATEGORIA AS PROD_CATEGORIA
FROM TB_VENDA V 
INNER JOIN TB_CLIENTE C ON V.ID_CLIENTE_FK = C.ID
INNER JOIN TB_PRODUTO_QUANTIDADE PQ ON PQ.ID_VENDA_FK = V.ID
INNER JOIN TB_PRODUTO P ON P.ID = PQ.ID_PRODUTO_FK
WHERE V.CODIGO = 'A1';

-- Consulta de todos os produtos com quantidade
SELECT PQ.ID, PQ.QUANTIDADE, PQ.VALOR_TOTAL,
       P.ID AS ID_PRODUTO, P.CODIGO, P.NOME, P.DESCRICAO, P.VALOR, P.CATEGORIA
FROM TB_PRODUTO_QUANTIDADE PQ
INNER JOIN TB_PRODUTO P ON P.ID = PQ.ID_PRODUTO_FK;
